---
spring:
  profiles:
    default: local

logging:
  level:
    org.springframework.ws.server.endpoint: DEBUG

---
spring:
  config:
    activate:    
      on-profile: local

---
spring:
  config:
    activate:    
      on-profile: unittest
